Import('dev source_path')

if dev.is_win32():
	env, target, sources = dev.prepare_build(source_path, 'aintl', '*.c', in_bin=False)

	if env['CC'] == 'cl': # MSVC
		empty_str = '\\"\\"'
	else:
		empty_str = '\'""\''
	env.Append(CPPDEFINES = ['LOCALEDIR=' + empty_str, 'LOCALE_ALIAS_PATH=' + empty_str,
		'INSTALLDIR=' + empty_str, 'LIBDIR=' + empty_str, 'IN_LIBINTL', 'ENABLE_RELOCATABLE=1',
		'NO_XMALLOC', 'HAVE_CONFIG_H', 'set_relocation_prefix=libintl_set_relocation_prefix',
		'relocate=libintl_relocate'])
	env.Append(CPPPATH='#/intl')

	dev.env.Append(LIBS=['aintl'])
	import os
	dev.env.Append(LIBPATH=[os.path.dirname(target)])
	ret = env.StaticLibrary(target, sources)
	Return('ret')

else:
	print "intl only built on win32"

Return()
