Import('dev source_path')

env, target, sources = dev.prepare_build(source_path, 'miniupnpc', source_glob = '*.c', in_bin = False)

if dev.is_win32():
	env.Append(CPPDEFINES = ['STATICLIB', '_WIN32_WINNT=0x501', '_WIN32_IE=0x501', 'WINVER=0x501', 'WIN32_LEAN_AND_MEAN'])
	if env['CC'] == 'cl': # MSVC
		env.Append(CPPDEFINES = ['WIN32'])
		env.Append(CPPPATH = ['vc'])

ret = env.StaticLibrary(target, sources)

Return('ret')
