Import('dev source_path')

if not dev.is_win32():
	Return()

env, target, sources = dev.prepare_build(source_path, 'TestPlugin', source_glob = '*.cpp', in_bin = False)

env.Append(CPPPATH = ['#/pluginsdk/cpp'])

res = env.RES(dev.get_sources(source_path, '*.rc'))
env.Depends(res, 'resource.h')

if 'g++' in env['LINK']:
	env.Append(SHLINKFLAGS = '-Wl,--add-stdcall-alias')
elif 'link' in env['LINK']:
	env.Append(SHLINKFLAGS = '/EXPORT:pluginInit')

ret = dev.build_lib(env, target, [sources, res, dev.boost], shared = True)
Return('ret')
