Import('dev source_path')

env, target, sources = dev.prepare_build(source_path, 'geoip', source_glob = '*.c', in_bin = False)

if dev.is_win32():
	env.Append(CPPDEFINES = ['HAVE_STDINT_H=1', 'PACKAGE_VERSION=0'])

	if 'msvc' in env['TOOLS']:
		env.Append(CPPDEFINES = ['ssize_t=SSIZE_T'])

ret = dev.build_lib(env, target, sources, dev.c_lib)
Return('ret')
