Import('dev source_path')

# only for MinGW
if 'gcc' not in dev.env['TOOLS']:
	Return()

env, target, sources = dev.prepare_build(source_path, 'dwarf', source_glob = '*.c', in_bin = False)

if dev.is_win32():
	env.Append(CPPDEFINES = ['WIN32', '_WIN32_WINNT=0x501', '_WIN32_IE=0x501', 'WINVER=0x501', 'WIN32_LEAN_AND_MEAN'])
env.Append(CPPPATH = ['#/dwarf'])

ret = dev.build_lib(env, target, sources)
Return('ret')
