Import('dev source_path')

env, target, sources = dev.prepare_build(source_path, 'lua', '*.c', in_bin = False)

if dev.is_win32():
	env.Append(CPPDEFINES = ['WIN32'])
else:
	env.Append(CPPDEFINES = ['LUA_USE_LINUX=1'])
	env.Append(LIBS = ['m', 'dl'])

ret = dev.build_lib(env, target, sources)
Return('ret')
