<dl style="margin-left: 40px;">
	<dt>Get file list</dt>
	<dd>Download the file list of the selected users.</dd>
	<dt>Browse file list</dt>
	<dd>Download only the required pieces of the file lists of the selected users.
	Only available in ADC hubs.</dd>
	<dt>Match queue</dt>
	<dd>Matches the files in your download queue to the file lists of the selected
	users. 2 files are considered to be the same if their TTH is the same. If matches are found in one user's file list,
	she will be added as a source for the relevant downloads.</dd>
	<dt>Send private message</dt>
	<dd>Open <a href="window_pm.html">private message</a> windows to chat privately with the selected users.</dd>
	<dt>Add to favorites</dt>
	<dd>Adds the selected users to your <a href="window_favorite_users.html">Favorite Users</a> list.</dd>
	<dt>Grant extra slot</dt>
	<dd>Beyond your set slots an extra upload slot will be given to the selected users until the
	end of the current DC++ session.</dd>
	<dt>Remove user from queue</dt>
	<dd>Removes the selected user from the source list of all queued files. Pending filelist requests
	will be removed as well.</dd>
</dl>
