<dl style="margin-left: 40px;">
  <dt>Remove</dt>
  <dd>Deletes the actual item from the list. If the corresponding setting in
      <a href="settings_windows.html#confirmitem">Confirm dialog options</a> is enabled,
      you will be prompted before the removal.</dd>
  <dt>Remove all</dt>
  <dd>Deletes all the selected items from the list. If the corresponding setting in
      <a href="settings_windows.html#confirmitem">Confirm dialog options</a> is enabled,
      you will be prompted before the removal.</dd>
	<dt>Copy</dt>
	<dd>Allows copying the content of any column to the clipboard. An &quot;All columns&quot;
	command is available as well to gather all the columns in the copied text (one column per
	copied line).</dd>
</dl>
