Import('dev source_path')

env, target, sources = dev.prepare_build(source_path, 'dwt', in_bin = False, recursive=True)

env.Append(CPPPATH = ['#/dwt/include'])

def get_msvcproj_files(env):
	def parse_patterns(patterns):
		array = []
		for pattern in patterns:
			for file in env.Glob('#/dwt/' + pattern):
				array.append(file)
		return array
	return (parse_patterns(['include/dwt/*.h', 'include/dwt/*/*.h', 'include/dwt/*/*/*.h']),
			parse_patterns(['src/*.cpp', 'src/*/*.cpp', 'src/*/*/*.cpp']))

ret = dev.build_lib(env, target, sources, get_msvcproj_files, 'dwt')

Return('ret')
