Import('dev source_path')

env, target, sources = dev.prepare_build(source_path, 'SamplePlugin', source_glob = '*.c', in_bin = False)

env.Append(CPPPATH = ['#/dcpp'])

ret = dev.build_lib(env, target, sources, shared = True)
