Import('dev source_path')

env, target, sources = dev.prepare_build(source_path, 'ExamplePlugin', source_glob = '*.c', in_bin = False)

res = env.RES(dev.get_sources(source_path, '*.rc'))
env.Depends(res, 'resource.h')

env.Append(CPPPATH = ['#/pluginsdk/c'])

if 'g++' in env['LINK']:
	env.Append(SHLINKFLAGS = '-Wl,--add-stdcall-alias')
elif 'link' in env['LINK']:
	env.Append(SHLINKFLAGS = '/EXPORT:pluginInit')

ret = dev.build_lib(env, target, [sources, res], shared = True)
Return('ret')
