Import('dev source_path')

env, target, sources = dev.prepare_build(source_path, 'archive', source_glob = '*.c', in_bin = False)

env.Append(CPPDEFINES = ['HAVE_CONFIG_H', 'LIBARCHIVE_STATIC'])

env.Append(CPPPATH = ['#/bzip2', '#/zlib'])

ret = dev.build_lib(env, target, sources, dev.c_lib)
Return('ret')
