Import('dev source_path')

if not dev.is_win32():
	Return()

env, target, sources = dev.prepare_build(source_path, 'DevPlugin', source_glob = '*.cpp', in_bin = False)

env.Append(CPPPATH = ['#/dcpp'])

res = env.RES(dev.get_sources(source_path, '*.rc'))
env.Depends(res, 'resource.h')

if 'g++' in env['LINK']:
	env.Append(SHLINKFLAGS = '-Wl,--add-stdcall-alias')
elif 'link' in env['LINK']:
	sources.append('Plugin.def')

ret = dev.build_lib(env, target, [sources, res], shared = True)
Return('ret')
