Import('dev source_path')

env, target, sources = dev.prepare_build(source_path, 'dwt', in_bin = False)

env.Append(CPPPATH = ['#/dwt/include'])

ret = [dev.build_lib(env, target, sources), dev.build('win32/')]
Return('ret')
