# vim: set filetype=py

Import('dev source_path')

env, target, sources = dev.prepare_build(source_path, 'dcpp', in_bin = False, precompiled_header = 'stdinc')

dev.add_boost(env)
dev.add_dcpp(env)
dev.add_intl(env)
dev.add_openssl(env)

env.Append(CPPDEFINES = ['BUILDING_DCPP=1'])

headers=dev.get_sources(source_path, "*.h")
dev.i18n(source_path, env, [sources, headers], 'libdcpp')

ret = dev.build_lib(env, target, sources, dev.cpp_lib)

if ret:
	revno = '#/dcpp/version-revno.inc'
	from gen_revno import gen_revno
	env.Command(revno, None, Action(gen_revno, 'Generating $TARGET'))
	env.Depends(sources, revno)
	env.AlwaysBuild(revno)

Return('ret')
