Import('dev source_path')

env, target, sources = dev.prepare_build(source_path, 'ScriptPlugin', source_glob = '*.cpp', in_bin = False)

env.Append(CPPPATH = ['#/pluginsdk/cpp', 'lua'])

res = env.RES(dev.get_sources(source_path, '*.rc'))
env.Depends(res, 'resource.h')

if 'g++' in env['LINK']:
	env.Append(SHLINKFLAGS = '-Wl,--add-stdcall-alias')
elif 'link' in env['LINK'] and env['arch'] == 'x86':
	sources.append('Plugin.def')

ret = dev.build_lib(env, target, [sources, res, dev.build('lua/'), dev.boost], shared = True)
Return('ret')
