Import('dev source_path')

env, target, sources = dev.prepare_build(source_path, 'zlib', source_glob = '*.c', in_bin = False)

env.Append(CPPDEFINES = ['CASESENSITIVITYDEFAULT_YES'])

ret = dev.build_lib(env, target, sources, dev.c_lib)
Return('ret')
